<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="Home.aspx.cs" Inherits="Pages.Pages_Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <img id="Img3" runat="server" src="~/Images/coffee1.png" class="imgLeft" />
    <h3>Title 1</h3>
    <p>Coffee is a brewed drink prepared from roasted coffee beans, which are the seeds of "berries" from the Coffea plant. Coffee plants are cultivated in over 70 countries, primarily in the equatorial regions of the Americas, Southeast Asia, India and Africa. The two most commonly grown are the highly regarded arabica, and the less sophisticated but stronger and more hardy robusta. The latter is resistant to the coffee leaf rust, Hemileia vastatrix, but has a more bitter taste. Once ripe, coffee beans are picked, processed, and dried. Green (unroasted) coffee beans are one of the most traded agricultural commodities in the world. Once traded, the beans are roasted to varying degrees, depending on the desired flavor, before being ground and brewed to create coffee.</p>
    <img id="Img2" runat="server" src="~/Images/coffee2.png" class="imgRight" />
    <h3>Title 2</h3>
    <p>Coffee is slightly acidic (pH 5.0–5.1) and can have a stimulating effect on humans because of its caffeine content. Coffee is one of the most popular drinks in the world. It can be prepared and presented in a variety of ways (e.g., espresso, cappucino, cafe latte, etc.). It is usually served hot, although iced coffee is also served. The effect of coffee on human health has been a subject of many studies; however, results have varied in terms of coffee's relative benefit. The majority of recent research suggests that moderate coffee consumption is benign or mildly beneficial in healthy adults. However, the diterpenes in coffee may increase the risk of heart disease.

Coffee cultivation first took place in Southern Arabia. The earliest credible evidence of coffee-drinking appears in the middle of the 15th century in the Sufi shrines of Yemen. In the Horn of Africa and Yemen, coffee was used in local religious ceremonies. As these ceremonies conflicted with the beliefs of the Christian church, the Ethiopian Church banned the secular consumption of coffee until the reign of Emperor Menelik II. The beverage was also banned in Ottoman Turkey during the 17th century for political reasons, and was associated with rebellious political activities in Europe.</p>
    <img id="Img1" runat="server" src="~/Images/coffee3.png" class="imgLeft" />
    <h3>Title 3</h3>
    <p>Coffee is a major export commodity: it was the top agricultural export for twelve countries in 2004, the world's seventh-largest legal agricultural export by value in 2005, and "the second most valuable commodity exported by developing countries," from 1970 to circa 2000. This last fact is frequently misstated; see commodity market, below. Further, green (unroasted) coffee is one of the most traded agricultural commodities in the world. Some controversy is associated with coffee cultivation and its impact on the environment. Consequently, fair trade and organic coffee are an expanding market.</p>
</asp:Content>
